# Home Assistant Helper Groups Configuration
# Documentation: https://www.home-assistant.io/integrations/group/

# Target Temperature Helpers (input_number)
# These can be modified by automations and persist across restarts
input_number:
  wohnzimmer_kuche_zieltemperatur:
    name: 'Wohnzimmer & Küche Zieltemperatur'
    min: 15
    max: 25
    step: 0.5
    initial: 22
    unit_of_measurement: '°C'
    icon: mdi:thermometer

  tim_buro_schlafzimmer_zieltemperatur:
    name: 'Tim Büro & Schlafzimmer Zieltemperatur'
    min: 15
    max: 25
    step: 0.5
    initial: 22
    unit_of_measurement: '°C'
    icon: mdi:thermometer

# Temperature Sensor Groups (arithmetic mean)
sensor:
  - platform: group
    name: 'Küche Temperatur'
    unique_id: kuche_temperatur
    type: mean
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    ignore_non_numeric: true
    entities:
      - sensor.kuche_thermostat_1_temperature
      - sensor.kuche_thermostat_2_temperature
      - sensor.kuche_thermometer_temperature

  - platform: group
    name: 'Wohnzimmer Temperatur'
    unique_id: wohnzimmer_temperatur
    type: mean
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    ignore_non_numeric: true
    entities:
      # - sensor.wohnzimmer_thermostat_1_temperature
      - sensor.wohnzimmer_thermost_2_temperature
      - sensor.wohnzimmer_thermometer_temperature

  - platform: group
    name: 'Tim Büro & Schlafzimmer Temperatur'
    unique_id: tim_buro_schlafzimmer_temperatur
    type: mean
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    ignore_non_numeric: true
    entities:
      - sensor.buro_thermometer_temperature
      - sensor.buro_thermostat_temperature
      - sensor.tim_schlafzimmer_thermometer_temperature

  # Humidity Sensor Groups (arithmetic mean)
  - platform: group
    name: 'Küche Luftfeuchtigkeit'
    unique_id: kuche_luftfeuchtigkeit
    type: mean
    device_class: humidity
    state_class: measurement
    unit_of_measurement: '%'
    ignore_non_numeric: true
    entities:
      - sensor.kuche_thermostat_1_humidity
      - sensor.kuche_thermostat_2_humidity
      - sensor.kuche_thermometer_humidity

  - platform: group
    name: 'Wohnzimmer Luftfeuchtigkeit'
    unique_id: wohnzimmer_luftfeuchtigkeit
    type: mean
    device_class: humidity
    state_class: measurement
    unit_of_measurement: '%'
    ignore_non_numeric: true
    entities:
      - sensor.wohnzimmer_thermostat_1_humidity
      - sensor.wohnzimmer_thermost_2_humidity
      - sensor.wohnzimmer_thermometer_humidity

  - platform: group
    name: 'Tim Büro & Schlafzimmer Luftfeuchtigkeit'
    unique_id: tim_buro_schlafzimmer_luftfeuchtigkeit
    type: mean
    device_class: humidity
    state_class: measurement
    unit_of_measurement: '%'
    ignore_non_numeric: true
    entities:
      - sensor.buro_thermometer_humidity
      - sensor.buro_thermostat_humidity
      - sensor.tim_schlafzimmer_thermometer_humidity

# Binary Sensor Groups (window/door sensors)
binary_sensor:
  - platform: group
    name: 'Küche & Wohnzimmer Fenster Sensoren'
    unique_id: kuche_wohnzimmer_fenster_sensoren
    device_class: window
    entities:
      - binary_sensor.terrassentur_door
      - binary_sensor.wohnzimmer_fenster_door
      - binary_sensor.kuche_fenster_1_door
      - binary_sensor.kuche_fenster_2_door

  - platform: group
    name: 'Tim Büro & Schlafzimmer Fenster Sensoren'
    unique_id: tim_buro_schlafzimmer_fenster_sensoren
    device_class: window
    entities:
      - binary_sensor.balkontur_door
      - binary_sensor.buro_fenster_door
      - binary_sensor.tim_schlafzimmer_fenster_door

# Template Binary Sensors
template:
  - binary_sensor:
      # Power-based device usage detection
      - name: 'Wohnzimmer-TV Steckdose in use'
        unique_id: wohnzimmer_tv_steckdose_in_use
        device_class: power
        state: "{{ states('sensor.wohnzimmer_tv_steckdose_power') | float(0) > 5 }}"

      # Presence detection - individual
      - name: 'Tim Home'
        unique_id: tim_home
        device_class: presence
        state: "{{ states('person.tim') == 'home' }}"

      - name: 'Edith Home'
        unique_id: edith_home
        device_class: presence
        state: "{{ states('person.edith') == 'home' }}"

      # Presence detection - combined
      - name: 'Somebody Home'
        unique_id: somebody_home
        device_class: presence
        state: "{{ states('person.tim') == 'home' or states('person.edith') == 'home' }}"

      - name: 'Nobody is Home'
        unique_id: nobody_home
        device_class: presence
        state: "{{ states('person.tim') != 'home' and states('person.edith') != 'home' }}"

      # Room occupancy detection
      - name: 'Küche & Wohnzimmer in use'
        unique_id: kuche_wohnzimmer_in_use
        device_class: occupancy
        state: "{{ is_state('binary_sensor.wohnzimmer_tv_steckdose_in_use', 'on') }}"

      # Power-based device usage detection for Büro & Tim Schlafzimmer
      - name: 'Tim PC Steckdose in use'
        unique_id: tim_pc_steckdose_in_use
        device_class: power
        state: "{{ states('sensor.tim_pc_steckdose_power') | float(0) > 5 }}"

      - name: 'Tim TV Steckdose in use'
        unique_id: tim_tv_steckdose_in_use
        device_class: power
        state: "{{ states('sensor.tim_tv_steckdose_power') | float(0) > 5 }}"

      - name: 'Monitor in use'
        unique_id: monitor_in_use
        device_class: power
        state: "{{ is_state('switch.monitor', 'on') }}"

      - name: 'Büro & Tim Schlafzimmer in use'
        unique_id: buro_tim_schlafzimmer_in_use
        device_class: occupancy
        state: >
          {{ is_state('binary_sensor.tim_pc_steckdose_in_use', 'on')
             or is_state('binary_sensor.tim_tv_steckdose_in_use', 'on')
             or is_state('binary_sensor.monitor_in_use', 'on') }}

      # Time-based heating period detection
      - name: 'Wohnzimmer & Küche Daytime Heating Period'
        unique_id: wohnzimmer_kuche_daytime_heating_period
        icon: mdi:moon-waning-crescent
        state: >
          {% set day = now().weekday() %}
          {% set time_decimal = now().hour + now().minute / 60 %}
          {% if day >= 4 %}
            {# Weekend: Fri(4), Sat(5), Sun(6) - 8:00 to midnight #}
            {{ time_decimal >= 8.0 }}
          {% else %}
            {# Weekday: Mon(0)-Thu(3) - 7:30 to 22:00 #}
            {{ time_decimal >= 7.5 and time_decimal < 22.0 }}
          {% endif %}

      - name: 'Tim Daytime Heating Period'
        unique_id: tim_daytime_heating_period
        icon: mdi:moon-waning-crescent
        state: >
          {% set time_decimal = now().hour + now().minute / 60 %}
          {# Daytime: 9:00 to 01:00 (next day), Night: 01:00 to 09:00 #}
          {{ time_decimal >= 9.0 or time_decimal < 1.0 }}
