# Home Assistant Helper Groups Configuration
# Documentation: https://www.home-assistant.io/integrations/group/

# Temperature Sensor Groups (arithmetic mean)
sensor:
  - platform: group
    name: 'Küche Temperatur'
    unique_id: kuche_temperatur
    type: mean
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    ignore_non_numeric: true
    entities:
      - sensor.kuche_thermostat_1_temperature
      - sensor.kuche_thermostat_2_temperature

  - platform: group
    name: 'Wohnzimmer Temperatur'
    unique_id: wohnzimmer_temperatur
    type: mean
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    ignore_non_numeric: true
    entities:
      # - sensor.wohnzimmer_thermostat_1_temperature
      - sensor.wohnzimmer_thermost_2_temperature

  - platform: group
    name: 'Tim Büro & Schlafzimmer Temperatur'
    unique_id: tim_buro_schlafzimmer_temperatur
    type: mean
    device_class: temperature
    state_class: measurement
    unit_of_measurement: '°C'
    ignore_non_numeric: true
    entities:
      - sensor.tim_thermometer_temperature
      - sensor.buro_thermostat_temperature
      # - sensor.tim_schlafzimmer_thermostat_temperature

  # Humidity Sensor Groups (arithmetic mean)
  - platform: group
    name: 'Küche Luftfeuchtigkeit'
    unique_id: kuche_luftfeuchtigkeit
    type: mean
    device_class: humidity
    state_class: measurement
    unit_of_measurement: '%'
    ignore_non_numeric: true
    entities:
      - sensor.kuche_thermostat_1_humidity
      - sensor.kuche_thermostat_2_humidity

  - platform: group
    name: 'Wohnzimmer Luftfeuchtigkeit'
    unique_id: wohnzimmer_luftfeuchtigkeit
    type: mean
    device_class: humidity
    state_class: measurement
    unit_of_measurement: '%'
    ignore_non_numeric: true
    entities:
      - sensor.wohnzimmer_thermostat_1_humidity
      - sensor.wohnzimmer_thermost_2_humidity

  - platform: group
    name: 'Tim Büro & Schlafzimmer Luftfeuchtigkeit'
    unique_id: tim_buro_schlafzimmer_luftfeuchtigkeit
    type: mean
    device_class: humidity
    state_class: measurement
    unit_of_measurement: '%'
    ignore_non_numeric: true
    entities:
      - sensor.tim_thermometer_humidity
      - sensor.buro_thermostat_humidity
      # - sensor.tim_schlafzimmer_thermostat_humidity

# Binary Sensor Groups (window/door sensors)
binary_sensor:
  - platform: group
    name: 'Küche & Wohnzimmer Fenster Sensoren'
    unique_id: kuche_wohnzimmer_fenster_sensoren
    device_class: window
    entities:
      - binary_sensor.terrassentur
      - binary_sensor.wohnzimmer_fenster
      - binary_sensor.kuche_fenster_1
      - binary_sensor.kuche_fenster_2

  - platform: group
    name: 'Tim Büro & Schlafzimmer Fenster Sensoren'
    unique_id: tim_buro_schlafzimmer_fenster_sensoren
    device_class: window
    entities:
      - binary_sensor.balkontur
      - binary_sensor.buro_fenster
      - binary_sensor.tim_schlafzimmer_fenster

# Template Binary Sensors
template:
  - binary_sensor:
      # Power-based device usage detection
      - name: 'Wohnzimmer-TV Steckdose in use'
        unique_id: wohnzimmer_tv_steckdose_in_use
        device_class: power
        state: "{{ states('sensor.wohnzimmer_tv_steckdose_power') | float(0) > 5 }}"

      # Presence detection - individual
      - name: 'Tim Home'
        unique_id: tim_home
        device_class: presence
        state: "{{ states('person.tim') == 'home' }}"

      - name: 'Edith Home'
        unique_id: edith_home
        device_class: presence
        state: "{{ states('person.edith') == 'home' }}"

      # Presence detection - combined
      - name: 'Somebody Home'
        unique_id: somebody_home
        device_class: presence
        state: "{{ states('person.tim') == 'home' or states('person.edith') == 'home' }}"

      - name: 'Everyone Home'
        unique_id: everyone_home
        device_class: presence
        state: "{{ states('person.tim') == 'home' and states('person.edith') == 'home' }}"

      - name: 'Nobody is Home'
        unique_id: nobody_home
        device_class: presence
        state: "{{ states('person.tim') != 'home' and states('person.edith') != 'home' }}"

      # Room occupancy detection
      - name: 'Küche & Wohnzimmer in use'
        unique_id: kuche_wohnzimmer_in_use
        device_class: occupancy
        state: "{{ is_state('binary_sensor.wohnzimmer_tv_steckdose_in_use', 'on') }}"

      # Time-based heating period detection
      - name: 'Daytime Heating Period'
        unique_id: daytime_heating_period
        state: >
          {% set day = now().weekday() %}
          {% set time_decimal = now().hour + now().minute / 60 %}
          {% if day >= 4 %}
            {# Weekend: Fri(4), Sat(5), Sun(6) - 8:00 to midnight #}
            {{ time_decimal >= 8.0 }}
          {% else %}
            {# Weekday: Mon(0)-Thu(3) - 7:30 to 22:00 #}
            {{ time_decimal >= 7.5 and time_decimal < 22.0 }}
          {% endif %}
