" This is the .vimrc file

" Disable compatibility with the vi editor on which vim is based
set nocompatible

" Activate line numbers
set number
set relativenumber

" Enable Syntax Highlighting 
syntax on
syntax enable

" automatic text wrap if line gets too long
set wrap 

" show the matching opening bracket when typing the closing one
set showmatch

" highlight search results
set hlsearch 
" Show search results immediately and jump to the first match
set incsearch
" Ignore case in search term
set ignorecase
set smartcase

" Faster redrawing
set ttyfast

" Don't redraw while executing macros
set nolazyredraw

" show cursor position
set ruler

" show cmd line tab complete options as a menu
set wildmenu

" Indentation options
set autoindent
filetype plugin indent on

" Make backspace behave as expected
set backspace=indent,eol,start

" Delete trailing whitespaces at end of lines automatically before saving
augroup remove_trailing_whitespace
	autocmd!
	autocmd BufWritePre * :%s/\s\+$//e
augroup END

" Apply changes to vimrc immediately to current session
if has("autocmd")
	autocmd!
    autocmd bufwritepost .vimrc source $MYVIMRC
endif

" This line enables saving a file even if not root using w!!
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

command! Q q        " Bind :Q to :q
command! Wq wq      " Bind :Wq to :wq

" Set Leader key to , (comma)
let mapleader = ","

"Save by using Leader + w
nnoremap <Leader>w :w<CR>

" Set Vim colorscheme
colorscheme jellybeans
" Keep the terminal background and not the colorscheme background
hi Normal guibg=NONE ctermbg=NONE
hi NonText guibg=NONE ctermbg=NONE

" Activate Status Bar
set laststatus=2
hi StatusLine ctermbg=NONE ctermfg=darkgray
hi StatusLineNC ctermbg=NONE ctermfg=darkgray

" Disable mouse in normal and visual mode
" set mouse=n

" Disable mouse entirely
set mouse=a

" Activate undofile
if has('persistent_undo')
  " Keep undo files in their own directory
  if !isdirectory($HOME."/.vim/undodir")
	call mkdir($HOME."/.vim/undodir", "p", 0700)
  endif
  set undodir=~/.vim/undodir
  set undofile
endif



" Setup Linter

"Enable Signcolumn
set signcolumn=yes

source ~/.vim/autoload/plug.vim
call plug#begin('~/.vim/plugged')
" Add your plugins here
Plug 'dense-analysis/ale'
call plug#end()

" To configure the ALE plugin for a specific linter (gcc) and display virtual text for errors:
let g:syntastic_cpp_checkers = ['gcc']
let g:ale_virtualtext_cursor = 1

