{
  config,
  pkgs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    haskellPackages.cabal-install
    glib-networking
    libcanberra-gtk2
    libdvdcss
    vaapiVdpau
    libva-utils
    pipewire
    socat
    tree-sitter
    yubikey-manager
    pam_u2f
    opensc
    libfido2
    yubikey-personalization
    pam_u2f
    chromium
    pcsclite
    # pcsc-tools
    nss
    yubico-piv-tool
    nssTools
    libsForQt5.qt5.qtbase
    kdePackages.qtbase
    conda
    cmake
    composefs
    dos2unix
    libgcc
    jdk
    python3
    python3Packages.pip
    phpPackages.composer
    go
    gtk4.dev
    gobject-introspection
    gjs
    julia
    libadwaita
    libinput
    lld
    libllvm
    luarocks
    lua
    meson
    linux-pam
    openssl
    openssl.dev
    perl
    php
    pixman
    protobuf
    ruby
    typescript
    gnumake
    neovim
    gcc
    zig
    fzf
    black
    python3Packages.black
    pylint
    python3Packages.pylint
    isort
    python3Packages.isort
    stylua
    nodePackages.typescript-language-server
    nodePackages.vscode-langservers-extracted
    nodePackages.vscode-langservers-extracted
    nodePackages.svelte-language-server
    tailwindcss-language-server
    lua-language-server
    nodePackages.graphql-language-service-cli
    emmet-ls
    vimPlugins.nvim-treesitter-parsers.prisma
    tree-sitter-grammars.tree-sitter-prisma
    vimPlugins.vim-prisma
    vimPlugins.nvim-treesitter-parsers.regex
    vimPlugins.nvim-treesitter-parsers.bash
    vimPlugins.nvim-treesitter-parsers.markdown
    vimPlugins.nvim-treesitter-parsers.markdown_inline
    vimPlugins.mini-nvim
    pyright
    rust-analyzer
    prettierd
    eslint_d
    pkg-config
    gobject-introspection
    rustc
    cargo
    rustfmt
    clippy
    cargo-edit
    cargo-tauri
    cargo-expand
    sqlite
    at-spi2-atk
    atkmm
    cairo.dev
    gdk-pixbuf.dev
    glib.dev
    gobject-introspection.dev
    libgee.dev
    xorg.libX11.dev
    atk.dev
    graphene.dev
    harfbuzz.dev
    libsoup_3
    pango.dev
    webkitgtk_4_1
    zlib
  ];
}
